In [83]:
import pandas as pd
import numpy as np

In [84]:
df_bank = pd.read_csv(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto\Bruto\bank-additional.csv')
df_bank

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,19154,NaN,admin.,MARRIED,university.degree,0.0,0.0,0.0,cellular,618,...,1.4,"93,444","-36,1",NaN,"5228,1",yes,13-octubre-2015,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,26206,34.0,technician,MARRIED,professional.course,0.0,1.0,1.0,cellular,42,...,-0.1,"93,2",-42,NaN,"5195,8",no,17-marzo-2018,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,15046,NaN,blue-collar,SINGLE,basic.6y,0.0,1.0,0.0,cellular,391,...,1.4,"93,918","-42,7",NaN,"5228,1",no,15-septiembre-2016,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,15280,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674,...,1.4,"93,918","-42,7","4,958","5228,1",no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,27570,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104,...,-0.1,"93,2",-42,"4,021","5195,8",no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [85]:
df_bank.shape

(43000, 24)

In [86]:
df_bank.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='object')

In [87]:
df_bank.dtypes

Unnamed: 0          int64
age               float64
job                object
marital            object
education          object
default           float64
housing           float64
loan              float64
contact            object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx     object
cons.conf.idx      object
euribor3m          object
nr.employed        object
y                  object
date               object
latitude          float64
longitude         float64
id_                object
dtype: object

In [88]:
df_bank.drop('Unnamed: 0', axis = 1, inplace = True) #Eliminamos la columna 'unnamed: 0' por que no es de utilidad

In [89]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.5+ MB

In [90]:
df_bank.head(10)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
5,45.0,services,MARRIED,basic.9y,NaN,0.0,0.0,telephone,198,1,...,1.1,"93,994","-36,4","4,857",5191,no,26-septiembre-2015,24.689,-101.643,d63ede72-0b6d-45b1-8872-385ac6897f65
6,59.0,admin.,MARRIED,professional.course,0.0,0.0,0.0,telephone,139,1,...,1.1,"93,994","-36,4","4,857",5191,no,25-enero-2019,31.456,-94.561,5e3483e5-236d-437d-8351-541f9d09b9dd
7,NaN,blue-collar,MARRIED,NaN,NaN,0.0,0.0,telephone,217,1,...,1.1,"93,994","-36,4","4,857",5191,no,25-septiembre-2017,46.871,-122.235,87fdc08b-30ae-4dab-803f-561ecdf27ff0
8,24.0,technician,SINGLE,professional.course,0.0,1.0,0.0,telephone,380,1,...,1.1,"93,994","-36,4","4,857",5191,no,18-enero-2018,44.632,-85.811,87b79988-2be5-419d-88f4-56655852c565
9,25.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,50,1,...,1.1,"93,994","-36,4",NaN,5191,no,2-noviembre-2016,30.297,-117.382,ea6b7d04-9271-4c0a-a01f-07795d164aba

In [91]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.5+ MB

In [92]:
cols_numericas = ['cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed']

In [93]:
for col in cols_numericas: #creo un bucle for para cambiar las , por .  ya que en el resultado de la tabla me salía NA esas columnas al hacer el cambio de tipo de dato
        df_bank[col] = df_bank[col].str.replace(',', '.').str.strip()

In [96]:
df_bank

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191.0,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191.0,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,NaN,admin.,MARRIED,university.degree,0.0,0.0,0.0,cellular,618,2,...,1.4,93.444,-36.1,NaN,5228.1,yes,13-octubre-2015,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,34.0,technician,MARRIED,professional.course,0.0,1.0,1.0,cellular,42,7,...,-0.1,93.200,-42.0,NaN,5195.8,no,17-marzo-2018,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,NaN,blue-collar,SINGLE,basic.6y,0.0,1.0,0.0,cellular,391,2,...,1.4,93.918,-42.7,NaN,5228.1,no,15-septiembre-2016,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674,3,...,1.4,93.918,-42.7,4.958,5228.1,no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104,2,...,-0.1,93.200,-42.0,4.021,5195.8,no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [97]:
df_bank[cols_numericas] = df_bank[cols_numericas].apply(pd.to_numeric, errors='coerce') #cambio de tipo de dato de object a numero en columnas numericas
df_bank

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191.0,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191.0,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,NaN,admin.,MARRIED,university.degree,0.0,0.0,0.0,cellular,618,2,...,1.4,93.444,-36.1,NaN,5228.1,yes,13-octubre-2015,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,34.0,technician,MARRIED,professional.course,0.0,1.0,1.0,cellular,42,7,...,-0.1,93.200,-42.0,NaN,5195.8,no,17-marzo-2018,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,NaN,blue-collar,SINGLE,basic.6y,0.0,1.0,0.0,cellular,391,2,...,1.4,93.918,-42.7,NaN,5228.1,no,15-septiembre-2016,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674,3,...,1.4,93.918,-42.7,4.958,5228.1,no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104,2,...,-0.1,93.200,-42.0,4.021,5195.8,no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [98]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  float64
 15  cons.conf.idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr.employed     43000 non-null  float64
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(11), int64(4), object(8)
memory usage: 7.5+ MB

In [ ]:
# Reemplazar los meses en español por inglés, ya que si no, no se puede hacer el camvio de dato a la columna
meses = {
    'enero': 'January', 'febrero': 'February', 'marzo': 'March',
    'abril': 'April', 'mayo': 'May', 'junio': 'June',
    'julio': 'July', 'agosto': 'August', 'septiembre': 'September',
    'octubre': 'October', 'noviembre': 'November', 'diciembre': 'December'
}

df_bank['date'] = df_bank['date'].str.lower()  # Por si hay mayúsculas
for es, en in meses.items():
    df_bank['date'] = df_bank['date'].str.replace(es, en, regex=False)

In [112]:
df_bank['date'] = pd.to_datetime(df_bank['date']) #cambiamos la columna de fecha
df_bank

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,<NA>,housemaid,MARRIED,basic.4y,False,False,False,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57,services,MARRIED,high.school,True,False,False,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37,services,MARRIED,high.school,False,True,False,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40,admin.,MARRIED,basic.6y,False,False,False,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56,services,MARRIED,high.school,False,False,True,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,<NA>,admin.,MARRIED,university.degree,False,False,False,cellular,618,2,...,1.4,93.444,-36.1,NaN,5228.1,yes,2015-10-13,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,34,technician,MARRIED,professional.course,False,True,True,cellular,42,7,...,-0.1,93.200,-42.0,NaN,5195.8,no,2018-03-17,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,<NA>,blue-collar,SINGLE,basic.6y,False,True,False,cellular,391,2,...,1.4,93.918,-42.7,NaN,5228.1,no,2016-09-15,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,<NA>,admin.,MARRIED,university.degree,True,False,False,cellular,674,3,...,1.4,93.918,-42.7,4.958,5228.1,no,2019-09-23,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,<NA>,unemployed,SINGLE,university.degree,False,False,True,cellular,104,2,...,-0.1,93.200,-42.0,4.021,5195.8,no,2019-11-06,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [113]:
cols_cat = ['job', 'marital', 'education', 'contact', 'poutcome']
df_bank[cols_cat] = df_bank[cols_cat].astype('category')

In [114]:
df_bank['age'] = df_bank['age'].astype('Int64')

In [105]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  category
 2   marital         42915 non-null  category
 3   education       41193 non-null  category
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  category
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  category
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  float64
 15  cons.conf.idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr.employed     43000 non-null  float64
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: Int64(1), category(5), datetime64[ns](1), float64(10), int64(4), object(2)
memory usage: 6.2+ MB

In [106]:
df_bank['default'].describe()

count    34019.000000
mean         0.000088
std          0.009390
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: default, dtype: float64

In [107]:
df_bank['housing'].describe()

count    41974.000000
mean         0.535998
std          0.498708
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: housing, dtype: float64

In [108]:
df_bank['loan'].describe() #las tres columnas podrian ser booleanos

count    41974.000000
mean         0.155620
std          0.362499
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: loan, dtype: float64

In [109]:
cols_bool = ['default', 'housing', 'loan']
df_bank[cols_bool] = df_bank[cols_bool].astype(bool)
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  category
 2   marital         42915 non-null  category
 3   education       41193 non-null  category
 4   default         43000 non-null  bool
 5   housing         43000 non-null  bool
 6   loan            43000 non-null  bool
 7   contact         43000 non-null  category
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  category
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  float64
 15  cons.conf.idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr.employed     43000 non-null  float64
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: Int64(1), bool(3), category(5), datetime64[ns](1), float64(7), int64(4), object(2)
memory usage: 5.3+ MB

In [110]:
df_bank

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,<NA>,housemaid,MARRIED,basic.4y,False,False,False,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57,services,MARRIED,high.school,True,False,False,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37,services,MARRIED,high.school,False,True,False,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40,admin.,MARRIED,basic.6y,False,False,False,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56,services,MARRIED,high.school,False,False,True,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191.0,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,<NA>,admin.,MARRIED,university.degree,False,False,False,cellular,618,2,...,1.4,93.444,-36.1,NaN,5228.1,yes,2015-10-13,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,34,technician,MARRIED,professional.course,False,True,True,cellular,42,7,...,-0.1,93.200,-42.0,NaN,5195.8,no,2018-03-17,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,<NA>,blue-collar,SINGLE,basic.6y,False,True,False,cellular,391,2,...,1.4,93.918,-42.7,NaN,5228.1,no,2016-09-15,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,<NA>,admin.,MARRIED,university.degree,True,False,False,cellular,674,3,...,1.4,93.918,-42.7,4.958,5228.1,no,2019-09-23,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,<NA>,unemployed,SINGLE,university.degree,False,False,True,cellular,104,2,...,-0.1,93.200,-42.0,4.021,5195.8,no,2019-11-06,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [111]:
df_bank.describe().T

,count,mean,min,25%,50%,75%,max,std
age,37880.0,39.977112,17.0,32.0,38.0,47.0,98.0,10.437957
duration,43000.0,257.739279,0.0,102.0,179.0,319.0,4918.0,258.666033
campaign,43000.0,2.567233,1.0,1.0,2.0,3.0,56.0,2.772294
pdays,43000.0,962.330953,0.0,999.0,999.0,999.0,999.0,187.260394
previous,43000.0,0.174023,0.0,0.0,0.0,0.0,7.0,0.497366
emp.var.rate,43000.0,0.077128,-3.4,-1.8,1.1,1.4,1.4,1.573898
cons.price.idx,42529.0,93.574219,92.201,93.075,93.749,93.994,94.767,0.579548
cons.conf.idx,43000.0,-40.509049,-50.8,-42.7,-41.8,-36.4,-26.9,4.637186
euribor3m,33744.0,3.616521,0.634,1.344,4.857,4.961,5.045,1.737117
nr.employed,43000.0,5166.852602,4963.6,5099.1,5191.0,5228.1,5228.1,72.411125
date,42752,2017-07-01 19:55:11.676646656,2015-01-01 00:00:00,2016-04-01 00:00:00,2017-07-04 00:00:00,2018-10-01 06:00:00,2019-12-31 00:00:00,NaN
latitude,43000.0,36.856697,24.396,30.61475,36.761,43.11325,49.384,7.225948
longitude,43000.0,-95.939067,-124.997,-110.49425,-95.8995,-81.42775,-66.937,16.752282

## Cambios de datos ya realizados (en teoria), continuar con siguientes passos