In [1]:
import pandas as pd

In [ ]:
dfclientes = pd.read_parquet(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto/Limpio/clientes_clean.parquet')
dfbank = pd.read_parquet(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto/Limpio/bank_clean.parquet')

df_merge = pd.merge(dfbank, dfclientes, on="ID", how="left")
df_merge

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,y,date,latitude,longitude,ID,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,<NA>,housemaid,MARRIED,basic.4y,False,False,False,telephone,261,1,...,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57,services,MARRIED,high.school,True,False,False,telephone,149,1,...,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37,services,MARRIED,high.school,False,True,False,telephone,226,1,...,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40,admin.,MARRIED,basic.6y,False,False,False,telephone,151,1,...,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56,services,MARRIED,high.school,False,False,True,telephone,307,1,...,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,<NA>,admin.,MARRIED,university.degree,False,False,False,cellular,618,2,...,yes,2015-10-13,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638,68672,0,2,2014-03-08,22
42996,34,technician,MARRIED,professional.course,False,True,True,cellular,42,7,...,no,2018-03-17,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493,73578,0,2,2014-03-11,26
42997,<NA>,blue-collar,SINGLE,basic.6y,False,True,False,cellular,391,2,...,no,2016-09-15,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b,9816,2,2,2014-09-18,31
42998,<NA>,admin.,MARRIED,university.degree,True,False,False,cellular,674,3,...,no,2019-09-23,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4,156980,1,2,2014-05-17,7
42999,<NA>,unemployed,SINGLE,university.degree,False,False,True,cellular,104,2,...,no,2019-11-06,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6,139820,0,0,2014-09-29,1

In [4]:
print("Bank:", dfbank.shape[0])
print("Clientes:", dfclientes.shape[0])

Bank: 43000
Clientes: 43170

In [5]:
df_merge.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'ID', 'Income',
       'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth'],
      dtype='object')

In [ ]:
df_merge.columns = (
    df_merge.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('[^a-z0-9_]', '', regex=True)
) #normalizamos nombres de las columnas

In [7]:
df_merge.head(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,y,date,latitude,longitude,id,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
0,<NA>,housemaid,MARRIED,basic.4y,False,False,False,telephone,261,1,...,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57,services,MARRIED,high.school,True,False,False,telephone,149,1,...,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37,services,MARRIED,high.school,False,True,False,telephone,226,1,...,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40,admin.,MARRIED,basic.6y,False,False,False,telephone,151,1,...,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56,services,MARRIED,high.school,False,False,True,telephone,307,1,...,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

In [8]:
print("Merge:", df_merge.shape[0]) #mantiene las filas de bank

Merge: 43000

In [9]:
df_merge_check = pd.merge(dfbank, dfclientes, on="ID", how="left", indicator=True)
print(df_merge_check['_merge'].value_counts()) #para comprobar cuantos ID hay en cada tabla comunes.

_merge
both          43000
left_only         0
right_only        0
Name: count, dtype: int64

In [10]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  Int64
 1   job                42655 non-null  category
 2   marital            42915 non-null  category
 3   education          41193 non-null  category
 4   default            43000 non-null  bool
 5   housing            43000 non-null  bool
 6   loan               43000 non-null  bool
 7   contact            43000 non-null  category
 8   duration           43000 non-null  int64
 9   campaign           43000 non-null  int64
 10  pdays              43000 non-null  int64
 11  previous           43000 non-null  int64
 12  poutcome           43000 non-null  category
 13  empvarrate         43000 non-null  float64
 14  conspriceidx       42529 non-null  float64
 15  consconfidx        43000 non-null  float64
 16  euribor3m          33744 non-null  float64
 17  nremployed         43000 non-null  float64
 18  y                  43000 non-null  object
 19  date               42752 non-null  datetime64[ns]
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id                 43000 non-null  object
 23  income             43000 non-null  int64
 24  kidhome            43000 non-null  int64
 25  teenhome           43000 non-null  int64
 26  dt_customer        43000 non-null  datetime64[ns]
 27  numwebvisitsmonth  43000 non-null  int64
dtypes: Int64(1), bool(3), category(5), datetime64[ns](2), float64(7), int64(8), object(2)
memory usage: 6.9+ MB

In [12]:
df_merge.describe().T

,count,mean,min,25%,50%,75%,max,std
age,37880.0,39.977112,17.0,32.0,38.0,47.0,98.0,10.437957
duration,43000.0,257.739279,0.0,102.0,179.0,319.0,4918.0,258.666033
campaign,43000.0,2.567233,1.0,1.0,2.0,3.0,56.0,2.772294
pdays,43000.0,962.330953,0.0,999.0,999.0,999.0,999.0,187.260394
previous,43000.0,0.174023,0.0,0.0,0.0,0.0,7.0,0.497366
empvarrate,43000.0,0.077128,-3.4,-1.8,1.1,1.4,1.4,1.573898
conspriceidx,42529.0,93.574219,92.201,93.075,93.749,93.994,94.767,0.579548
consconfidx,43000.0,-40.509049,-50.8,-42.7,-41.8,-36.4,-26.9,4.637186
euribor3m,33744.0,3.616521,0.634,1.344,4.857,4.961,5.045,1.737117
nremployed,43000.0,5166.852602,4963.6,5099.1,5191.0,5228.1,5228.1,72.411125
date,42752,2017-07-01 19:55:11.676646656,2015-01-01 00:00:00,2016-04-01 00:00:00,2017-07-04 00:00:00,2018-10-01 06:00:00,2019-12-31 00:00:00,NaN
latitude,43000.0,36.856697,24.396,30.61475,36.761,43.11325,49.384,7.225948
longitude,43000.0,-95.939067,-124.997,-110.49425,-95.8995,-81.42775,-66.937,16.752282
income,43000.0,93241.20007,5841.0,49610.0,93050.5,136744.5,180802.0,50498.316182
kidhome,43000.0,1.004791,0.0,0.0,1.0,2.0,2.0,0.815913
teenhome,43000.0,0.998605,0.0,0.0,1.0,2.0,2.0,0.815983
dt_customer,43000,2013-05-12 07:05:06.083720960,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-02 00:00:00,2014-03-29 00:00:00,2014-12-31 00:00:00,NaN
numwebvisitsmonth,43000.0,16.589698,1.0,9.0,17.0,25.0,32.0,9.239205